### ISSUE TITLE
Add support for merging in META information

### ISSUE THREAD

**Issue by jberger** [Leont/App-ModuleBuildTiny#1]
As discussed on IRC, it would be handy to be able to specify other META information which could be merged into the META.\* files. While Module::Metadata can detect some things, others, like repository/website information or `no_index` would be too hard to heuristically extract in any reasonable way. 

We have discussed using an external file. I originally proposed a perl file which could be do-loaded and then merged. @Leont has stated a preference for json, though the meta-spec version would have to be specified as a key. @dagolden has stated that CPAN::Meta::Merge could default to the most current version of CPAN::Meta, which would ease that somewhat, though the user should be encouraged to specify the version to avoid breakage later.

**Comment by Leont** [comment]
I've added this functionality in release 0.004, using a file called metamerge.{json,yml}

**Comment by karenetheridge** [comment]
This is really nice, and it makes MBT much more desirable to wrapper tools like Milla!
