### ISSUE TITLE
Meta data from .pod file

### ISSUE THREAD

**Issue by ronww** [Leont/App-ModuleBuildTiny#14]
Please support reading the meta data from the .pod file, not just the .pm file. Maybe have a --pod option to request this.

**Comment by Leont** [comment]
It would seem reasonable to prefer .pod over .pm, if you wouldn't want to use that it wouldn't be there.

**Comment by Leont** [comment]
This is actually more tricky than expected, because some metadata (`$VERSION` in particular) always needs to come from the `.pm` file, but other metadata could come from both.

**Comment by ronww** [comment]
Yes, I ran into that while testing possible proposals for code changes.

While I've come up with a working scheme for "falling back" on the pm file
for missing information, I've been hesitant to propose it.

In my situation, I'm working on generating POD from special comments -
comments similar to what Perl6 provides. Of course, it still makes sense to
include some POD in the pm file, which is just passed through as-is.

So, I've been working to enhance my POD generator to extract information
information from POD in the pm file.

That does lead to another to another idea I might propose. Still working on
a demonstration.

**Comment by jberger** [comment]
I don't understand what information you would want to extract from a .pod file if the .pm is present. Could you give an example? Also since the addition of the metamerge file it can be much easier to tweak up the discovered data with your own data.

**Comment by ronww** [comment]
On Sat, Mar 26, 2016 at 3:18 PM, Joel Berger notifications@github.com
wrote:

> I don't understand what information you would want to extract from a .pod
> file if the .pm is present. Could you give an example? Also since the
> addition of the metamerge file it can be much easier to tweak up the
> discovered data with your own data.

For various reasons, some projects put the documentation in a separate pod
file. Since some of the information extracted by mbtiny (and other similar
tools) is in the "pod comments", then if the POD is in a separate pod file,
then that file needs to be scanned.

Thinking more, it occurs to me that, in the general case, supporting a
separate pod file will require scanning both the pm and the pod files. I
can clean up and submit my proposed enhancement to App::ModuleBuildTiny to
support this.

For my situation, I could generate a metamerge.json file along side
generating the pod file. I do, however, wonder which other "distribution
build tools" also support metamerge and how.

**Comment by Leont** [comment]
> I do, however, wonder which other "distribution build tools" also support metamerge and how.

They don't.

**Comment by Leont** [comment]
This has been fixed in 0.034
