### ISSUE TITLE
uninit value at App/ModuleBuildTiny.pm line 57

### ISSUE THREAD

**Issue by ronww** [Leont/App-ModuleBuildTiny#15]
I did:
mbtiny regerate
mbtiny test

Got: Use of uninitialized value in numeric lt (<) at App/ModuleBuildTiny.pm line 57

After looking at the source, I deleted META.json, then ran "mbtiny test" and got:
    Creating new 'Build' script for 'xxxxxx'
    '.' is not recognized as an internal or external command,
    operable program or batch file.

Tried deleting Build.PL and rerunning, again.

Got: Can't open perl script "Build.PL": No such file or directory

**Comment by ronww** [comment]
"mbtiny dist" results in same error even if I delete META.json first.

**Comment by Leont** [comment]
Right. It seems the code assumes the existence of a cpanfile, despite my carefully not making that assumption for META.json and metamerge.

**Comment by Leont** [comment]
>  `'.' is not recognized as an internal or external command,`

And that sounds like I should make my code more Windows friendly (no `./` there)…

**Comment by Leont** [comment]
These issues should be fixed in 0.008
