### ISSUE TITLE
Invalid links to helper scripts

### ISSUE THREAD

**Issue by Grinnz** [Leont/App-ModuleBuildTiny#17]
scan_prereqs_cpanfile should be scan-prereqs-cpanfile. perl-reversion is an example script which is no longer indexed and uses the version rules of Perl::Version which are not quite the same as version.pm, perl-bump-version or perl-rewrite-version could be referenced instead.

**Comment by jberger** [comment]
Dan's modules are new and though I haven't looked at them yet they are
probably good given his history, and yet perl-reversion is not missing it
just needs a more direct link than the usual since brian packages it
strangely.

**Comment by Leont** [comment]
> scan_prereqs_cpanfile should be scan-prereqs-cpanfile.

That should be easy to fix.

> perl-reversion is an example script which is no longer indexed

That should be easy to fix too, with a little help from Brian.

>  uses the version rules of Perl::Version which are not quite the same as version.pm, perl-bump-version or perl-rewrite-version could be referenced instead.

The internals are a bit odd, but what difference does it make to the end-user? (genuine question, I have no idea)

**Comment by Grinnz** [comment]
It should work for any version tuples, but it is incompatible with decimal versions. For example, it will bump a version of '0.9' to '0.10'.

**Comment by Grinnz** [comment]
My scripts are of course just a suggestion, and any ideas for improvement would be welcome :)

**Comment by Leont** [comment]
> My scripts are of course just a suggestion, and any ideas for improvement would be welcome :)

Well, it's just the see also section, it's not like I can't link to both, really.

**Comment by Leont** [comment]
These links don't even exist anymore, so closing.
