### ISSUE TITLE
mbtiny regenerate includes $DISTNAME-$VERSION.tar.gz in MANIFEST

### ISSUE THREAD

**Issue by kentfredric** [Leont/App-ModuleBuildTiny#22]
```
mbtiny dist 
mbtiny regenerate
```

->

`MANIFEST` now contains `Some-Dist-Name-0.001.tar.gz`

This is typically undesirable, and should either 
- not happen at all by default
- give some kind of warning that this is happening and point out what file to augment to fix it.

**Comment by Leont** [comment]
Yeah, it's kind of dependent on a proper MANIFEST.SKIP. My minting branch does contain logic to add that, but it hasn't been merged into master yet.

**Comment by Leont** [comment]
> My minting branch does contain logic to add that, but it hasn't been merged into master yet.

That minter has been added. I'm still in doubt if I should add code to explicitly remove the generated tarballs explicitly on top of that.
