### ISSUE TITLE
Empty directory should be clearer about what is failing

### ISSUE THREAD

**Issue by kentfredric** [Leont/App-ModuleBuildTiny#23]
``` bash
mkdir /tmp/mbt-test
cd /tmp/mbt-test
mbtiny dist
# Can't call method "pod" on an undefined value at /home/kent/perl5/perlbrew/perls/5.24.0-RC5/lib/site_perl/5.24.0/App/ModuleBuildTiny.pm line 110.
```

I think the right thing to do here would be to assert that `$filename` on line 106 is expected to exist, 
as nothing really works without that, and subsequent failures in said file generate fatal errors anyway.

**Comment by Leont** [comment]
This should be fixed in 0.013
