### ISSUE TITLE
Symlink handling undefined, leads to Win32 unfriendly tars

### ISSUE THREAD

**Issue by kentfredric** [Leont/App-ModuleBuildTiny#30]
See https://github.com/kentnl/CPAN-Testers-TailLog/issues/3

I have the shortcut:

```
lib/Foo.pm
README.pod -> lib/Foo.pm
```

In order to convince Github to render Foo.pm as the README

This is apparently a viable hack on Dzil because Dzil converts symlinks to their contents.

But AMBT seems to preserve symlinks as-is.

```
curl -sLk https://cpan.metacpan.org/authors/id/K/KE/KENTNL/CPAN-Testers-TailLog-0.001001.tar.gz | tar -zvt  | grep -i READ 
lrwxr-xr-x kent/kent         0 2016-08-22 23:29 CPAN-Testers-TailLog-0.001001/README.pod -> lib/CPAN/Testers/TailLog.pm
```

**Comment by Leont** [comment]
The difference is due to me using `Archive::Tar->add_file` when possible when dzil uses `Archive::Tar->add_data`. The solution seems to be to set `$Archive::Tar::FOLLOW_SYMLINK` to `1`.

**Comment by kentfredric** [comment]
Well Dzil also has a "GatherDir" stage that just reads symlinks into files. So its cheating. ( I didn't happen to see any DZ::File:: subclass that preserved non-files )

**Comment by Leont** [comment]
[Fixed](https://github.com/Leont/app-modulebuildtiny/commit/b718730c1e5cb8c9b20b869edadd097fdc2a3f15) in 0.018
