### ISSUE TITLE
Optionally write out a config file

### ISSUE THREAD

**Issue by Ovid** [Leont/App-ModuleBuildTiny#47]
When I do this:

```
mbtint mint Some::Dist
```

I see this:

```
What is the author's name? Curtis "Ovid" Poe
What is the author's email? curtis.poe@gmail.com
What license do you want to use? [Perl_5]
```

It would be nice if it then prompted you to allow it to write out a config file with this information so that you no longer had to re-enter this information.

**Comment by Leont** [comment]
> It would be nice if it then prompted you to allow it to write out a config file with this information so that you no longer had to re-enter this information.

That's exactly what the `mbtiny setup` command does! 😉

I guess I really should write that "getting started with mbtiny" blogpost

**Comment by Ovid** [comment]
Ah. Thanks! I didn't see that down at the bottom. I'll close this :)

**Comment by Ovid** [comment]
And put that blog post prominently in the docs, maybe as `App::ModuleBuildTiny::Tutorial`?
