### ISSUE TITLE
Add proper license support

### ISSUE THREAD

**Issue by Leont** [Leont/App-ModuleBuildTiny#6]
Currently it is hard-coded to use the perl license, this is suboptimal. It should probably be detected from the source much like [[LicenseFromModule]](https://metacpan.org/pod/Dist::Zilla::Plugin::LicenseFromModule) does. It should probably also be able to generate a LICENSE file.

**Comment by powerman** [comment]
I've just tried to overwrite default "perl_5" license using metamerge.json, but it doesn't work - instead my "mit" license was added to licenses array after "perl_5". Is it possible to overwrite it somehow?

**Comment by Leont** [comment]
> I've just tried to overwrite default "perl_5" license using metamerge.json, but it doesn't work - instead my "mit" license was added to licenses array after "perl_5". Is it possible to overwrite it somehow?

The license should be in the documentation anyway, it makes more sense to extract it from there. Implementing that is tricky though, have have to refactor my code significantly to make that work out cleanly.

**Comment by powerman** [comment]
Actually it makes more sense to _inject_ it into documentation. :) LICENSE file and reference to it in module's POD/README isn't something module authors happy to craft by hand, just like META.json.

**Comment by jberger** [comment]
Except that unlike the META file, you don't keep regenerating the module's
pod. I think extracting from the doc makes sense.

**Comment by Leont** [comment]
Yeah, it's a valid and sensible workflow, but it doesn't fit well with the way ambt works.

**Comment by Leont** [comment]
I've added the license from POD logic to master. The LICENSE creation I'll leave for the minter.
